### ISSUE TITLE
Admin panel visual glitch in Firefox

### ISSUE THREAD

**Issue by jamesgecko** [Circa75/dropplets#200]
This is what the admin panel looks like in Firefox 22.0.

![dashboard](https://f.cloud.github.com/assets/44252/922428/e116a0d8-ff28-11e2-9faa-9f79a65caddc.png)

**Comment by tmwalton** [comment]
I decided to try out Dropplets. It looks pretty cool, but I came here because I am experiencing this same bug. I'm running Firefox Developer Edition 37.0a2 on Ubuntu.

**Comment by UsernameIsAReservedWord** [comment]
same here. Windows 8.1 x64, Firefox 35.0.1, EsasyPHP1.4.1 as dev test server.
