### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by graywolf** [Circa75/dropplets#313]
Hi,
I just installed dropplets a noticed one area where dropplets are.. let's say not as good as I hoped they would be. And that area is error reporting. I know I'm not without blame, but some sensible error message would be nice.

Particulary there were two moments where I felt error message is missing:

1) dropplets cannot create session - I would expect at least SOME error message about not being able to create session. I spent about half an hour going through sources and trying to figure out why login is not working until I noticed unability to create session.

2) unability to upload file - if /posts is not writable, there is just silence fail when trying to upload post. No error, nothing.

PS: but to make it clear, I really like dropplets, it's great idea behind them

**Comment by grubernd** [comment]
having the very same problem that login randomly fails i would appreciate how you solved your "unability to create session" case - or if you were not able to. as it might be a potential source for the "login fails" problem.
clearing session cookies didnt work here. currently dp on both firefox (worked once yesterday) and chrome (never worked) resists any attempt to login.
