### ISSUE TITLE
login silently fails

### ISSUE THREAD

**Issue by hjhtw** [Circa75/dropplets#356]
After uploading dropplets, I am able to create a password, but never able to login. When I enter my password, the page reloads, but the sidebar remains the same (it reads "Hello There!", prompts for a password to be entered, and does not offer any admin tools). The results are the same whether I enter the correct password or a false one. There is no error message.

Any ideas what could be the problem?

**Comment by grubernd** [comment]
same. although i could login once on firefox for a prolonged session, but never again. chrome failed from the beginning. cookies are allowed, get set and even clearing them didnt change a thing.
might be related to #313 concerning session-management.
