### ISSUE TITLE
Discussion: Project Future

### ISSUE THREAD

**Issue by Hibby** [Circa75/dropplets#364]
So - There's about 1300 people starred this project, 110 watching it and nearly 200 forks.

There's continuing discussion about incremental improvements and updates and a growing sense of dejection at the lack of progress. 

Personally, I really like the software - there's definitely room in my life for a flat file, simple blogging platform, but I've got concerns about running old, unmaintained code on my systems. 
Are there enough of us still engaged and interested to warrant a developerd fork of the project, with a group of people that can authorise pull requests so there's no single point of failure?

Has anyone started this, or is it a stupid idea?

**Comment by Circa75** [comment]
Cool... anyone else?

**Comment by benlk** [comment]
Sure. Like prisis, I'm not sure about time availability, but if there's a good list of development tickets, I'm willing to work on some of them.

**Comment by Circa75** [comment]
I'm not too concerned about time/availability, just that there is some sort of commitment. At the very least, as a group, we can keep the project alive and moving forward... even if it's slowly at first.

**Comment by tvdsluijs** [comment]
so is it worked on at the moment? Or should I find my flat file cms someware else?
I really like the simplicity of dropplets.... but any progress would be nice.

I'm a good enough php developer I guess. So if you need any help I would.... but not alone.

**Comment by tvdsluijs** [comment]
And if we work on this... shouldn't there be some sort of .. backlog with what people are working on? Just a idea :-)

**Comment by Circa75** [comment]
My hope is that I'll be able to pull together some sort of team with enough interest to pull together v2, but for now, if you plan on building something for the long haul, I would recommend something else.

**Comment by johnroper100** [comment]
Check out the newest updates!
