### ISSUE TITLE
Plans for v2

### ISSUE THREAD

**Issue by prisis** [Circa75/dropplets#368]
If you want we can discuss the version 2 here and make some plans :)

**Comment by pfinkbeiner** [comment]
So, I assume that there will be definitely a version 2 of dropplets @Circa75 ? If so, we can go further and propose some features we'd like to see in future. Furthermore, we should decide if we set up a complete new project structure or if we should invest some time to refactor the existing code.

**Comment by Circa75** [comment]
Yup... let's assume that there will definitely be a version 2. Like I said... I can't do it on my own, but it seems that won't be the case. Hoping to get more developers involved. Spread the word.

**Comment by benlk** [comment]
Proposal: **arbitrary post metadata**, accessible to the theme. Which means something like [YAML](https://en.wikipedia.org/wiki/YAML#Examples), performing like [Jekyll's front matter](http://jekyllrb.com/docs/frontmatter/).

**Comment by prisis** [comment]
How about if we make a hole new project of dropplets.
+ drop support for php 5.3
+ use psr-2 or symfony syntax
+ a new folder structure
+ use composer (for dev)
+ https://github.com/nikic/FastRoute for routing
+ new template system like plates, twig or something like my system where you can chose what you want use
+ use classes and stop mixing php and html

**Comment by jrsinclair** [comment]
Standardising some of the components that make up Dropplets as @prisis suggests is a good idea. A template system is definitely a good idea, and using a coding standard will help keep code quality consistent (note, I said *help*, not *enforce*).

**Comment by benlk** [comment]
As far as coding standards go, a styleguide for PHP and CSS/LESS/SASS would probably be useful. There are many available. [Here's an example](https://github.com/INN/docs/tree/master/style-guides/code). Maybe with that could be an `.editorconfig`.

@jrsinclair What do you mean a template system? There's already one in Dropplets, mostly using `<?php echo( $context_specific_variable ); ?>`

**Comment by jrsinclair** [comment]
Regarding template systems, I was just echoing @prisis. Something like [Twig](http://twig.sensiolabs.org/) or [Plates](http://platesphp.com/) or even [Handlebars](http://handlebarsjs.com/) gives you a syntax for templating that is a bit more concise and expressive than plain old php templates. Because they're a different syntax than regular PHP, it helps reinforce the separation of concerns. They also have the advantage that you can compile them to get slightly better performance.

The Drupal community 'recently' made the switch to using Twig for Drupal 8 after many years of old-style php templates.

**Comment by Circa75** [comment]
@jrsinclair I'm familiar with Handlebars and am definitely interested in integrating some sort of templating system for Dropplets.

@benlk Style preprocessing was definitely on my mind as well.

@prisis I'm thinking we should create a new branch for v2 rather than a new project... thoughts?

**Comment by prisis** [comment]
@Circa75 sorry :D, I did meant a new branch haha

Yeah some,  but give me 1-2 more days :)

**Comment by karloscarweber** [comment]
You get my vote for Handlebars templates. It's ridiculously easy to use and we can use it for any JavaScript temp laying as well.

**Comment by prisis** [comment]
I did start to work on structure for v2 :  https://github.com/prisis/dropplets/tree/develop

**Comment by prisis** [comment]
Hey guys, do you like the structure?

**Comment by Circa75** [comment]
Yeah... that looks good to me.

**Comment by prisis** [comment]
If you like to change something, say it :) else I will start to make the next steps

**Comment by Circa75** [comment]
It really does look good to me... anyone else have any input?

**Comment by grubernd** [comment]
switching to use neatly defined CommonMark (cmark) instead if the ambiguos defined original markdown would be awesome. in general usage nothing changes, but all the edge cases are now free of random results depending on which lib you used.
http://commonmark.org/
https://github.com/jgm/CommonMark

**Comment by jrsinclair** [comment]
Hmmm. I'd prefer [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) myself, but I can respect the reasoning behind using CommonMark.

**Comment by grubernd** [comment]
@jrsinclair .. me too, kind of. but in reallife usage i found the features from Extra not worth bothering and tables are just a pain to write.
and since there are some of the bigger players involved in the making of CommonMark my bet is that those specs will grow once the early nik-naks are ironed out, of which i havent found any myself.

**Comment by 2xAA** [comment]
What I'd love to see is an option to turn off the Dropplets button on every page and instead go to an admin page to sign in instead which then brings the control panel back if signed in.

I was going to write this into the current version of Dropplets, but if you're developing a V2 then I'll offer my services for the second version instead!

**Comment by benlk** [comment]
Similarly, I'd like an option to turn off the admin functions entirely - I don't use the web interface at all, and have received password reset emails in the past. I FTP new entries to the site.

**Comment by 2xAA** [comment]
Also, I'd like to see jQuery being either removed or taken away from the $ variable so you don't conflict with other libraries.

**Comment by prisis** [comment]
Hey, i will do next week a list with all future extensions.

I like to use https://github.com/thephpleague/flysystem to manage all files.

**Comment by anthonycl** [comment]
I haven't seen much progress on this with lots of potential. I've already made changes on my local copy just to make things work in the way I want them to. I think before version 2 is even considered we need to setup a process to review issues and pull request and merge them in fixing existing issues.

**Comment by prisis** [comment]
Im really sorry...
Right now i don't have much time to finish dropplets...
Im working on some components that i need, than i can start working on dropplets again...

**Comment by scotthorn** [comment]
I agree with @anthonycl and will contribute to this effort. IMO an overhaul with a php framework and composer would be cool... but a large undertaking that there doesn't seem to be much dev support for.

I'm also interested in moving or removing the front-end admin access. Currently I hide the toggle with css and added a small jquery snippet so show it when pressing CMD/CTRL + Shift + S:

    $(document).keydown(function(e){
          if( e.which === 83 && (e.ctrlKey || e.metaKey) && e.shiftKey ){
             $('#dp-dropplets-icon').toggle();
          }
    }); 

That won't protect from any crawling scripts, but makes the admin interface not viewable to my visitors.
