### ISSUE TITLE
Empty jpg files in cache

### ISSUE THREAD

**Issue by taylor-chen** [Circa75/dropplets#374]
i have jpg files in my /cache folder all of them are [twitter name].jpg with a size of 0b. I have `$index_cache = 'off';` in /dropplets/settings.php. How can i stop these files from being generated?

**Comment by lightningwhelk** [comment]
In the dropplets/functions.php file, line 312, there is this assignment:

    $image_url = 'http://dropplets.com/profiles/?id='.$username.'';    

At the moment, the URL will not respond with a valid image. As a cheap hack, you can use this as a replacement line:

    $image_url = 'https://twitter.com/'.$username.'/profile_image?size=normal';

which uses a hack to Twitter's web site (not the official APIs) that will get the normal size for a given Twitter name.

I wonder if the author meant to provide a service via dropplets.com that would use the Twitter API to get avatars, and ran across problems?

**Comment by anthonycl** [comment]
Btw, if you use size=bigger, you get a better quality larger image. :)

**Comment by thelaurence** [comment]
Maybe try deleting this line in /index.php:

    $blog_image = 'https://api.twitter.com/1/users/profile_image?screen_name='.$blog_twitter.'&size=bigger';

Trying to get a profile image this way in a browser returns a nice message from twitter:

    The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.

If it's trying to download a .jpg to the /cache directory and getting a plaintext error message in response, that might be the source of the empty .jpg files. I suppose the fact that it's still trying to use a deactivated API is not surprising given that the last release of the dropplets was almost two years ago.
