### ISSUE TITLE
MAMP / Local Development

### ISSUE THREAD

**Issue by onyudo** [Circa75/dropplets#375]
Forgive me for the noob/redundant question... I'm trying to install this locally via MAMP 3.1 and keep getting "It seems that your config folder is not writable, please add the necessary permissions."

What config file *exactly* should i be looking for and what *exactly* needs to be changed?

Also... Anybody have issues hosting Dropplets on MediaTemple?

**Comment by jessycormier** [comment]
I think they are talking about the permissions on the file/folder. Files and/or Folders can have write/read/execute permissions. You should be able to change this. Are you on windows or mac?
(google change file/folder permissions for a quick how to)

**Comment by onyudo** [comment]
Thanks for the reply! I am on a Mac, if that helps... I have been changing permissions on files like crazy and none of my attempts have gotten me past that error message.

**Comment by benlk** [comment]
What user does your apache server run as? And are your dropplets folder and all files and subfolders in it owned by that user, or accessible by a group your apache user is in?

**Comment by onyudo** [comment]
Thanks to both of you for taking the time to write and make suggestions. Unfortunately, I have had to move along to another platform due to the project's time constraints. Dropplets looks great—and I'm sure that I'll keep an eye on it—but I have to get this thing moving. Cheers!
