### ISSUE TITLE
RSS gives 404

### ISSUE THREAD

**Issue by shooshpakka** [Circa75/dropplets#376]
Hello and thank you for a nice masterpiece of minimalistic platform.

I've got strange issue with dropplets — everything seems fine, but nor rss, nor atom feeds seems to be broken. Platform just gives me 404.

http://shoo.pro/rss
http://shoo.pro/atom

Is it possible to fix it somehow?

**Comment by benlk** [comment]
Does your .htaccess file have redirects in place for the rss or atom feeds? It should not. 

Are you seeing any PHP errors in the server logs?

**Comment by shooshpakka** [comment]
Thanks for answer!

Nginx don't use .htaccess, and my redirection rules for it is quite simple, but you told me about logs, and here's what I see:

2015/05/02 10:18:04 [error] 15104#0: *19 FastCGI sent in stderr: "PHP Warning:  file(./posts/rss.md) [<a href='function.file'>function.file</a>]: failed to open stream: No such file or directory in /var/www/shoo.pro/index.php on line 256" while reading response header from upstream, client: 37.146.154.215, server: www.shoo.pro, request: "GET /rss HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "shoo.pro"

2015/05/02 10:22:25 [error] 15105#0: *270 FastCGI sent in stderr: "PHP Warning:  file(./posts/atom.md) [<a href='function.file'>function.file</a>]: failed to open stream: No such file or directory in /var/www/shoo.pro/index.php on line 256" while reading response header from upstream, client: 37.146.154.215, server: www.shoo.pro, request: "GET /atom HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "shoo.pro"

Dropplets thoughts that /rss and /atom URLs should be... postings?

How should I fix it?

**Comment by Zenyai** [comment]
For a quick hack use yourdomain.com/index.php?filename=rss

**Comment by shooshpakka** [comment]
Thank you @Zenyai — works for me.
