### ISSUE TITLE
Needs a lot of work

### ISSUE THREAD

**Issue by ank99** [Circa75/dropplets#377]
I admit I did give it a try. About an hour or so, which is a lot more than I give to any software to get it running, especially if it claims it should be a 30 second install. For one somebody should write a one page instruction "manual" on how to install the thing. Not everyone operates from a web hosting account. Need to say what permissions are required and where. The video that (I assume) was supposed to be an install guide does not work on my Linux platform.
Then gibberish on the top left corner after resolving the permissions problems which I managed to pass through thanks to another user reporting this.
Then trying to upload the first post I get these errors:
PHP Notice:  Use of undefined constant length - assumed 'length' in /var/www/html/dom.org/dropplets-blog/dropplets/functions.php on line 157, referer: http://www.dom.org/dropplets-blog/
 PHP Notice:  Undefined variable: login_error in /var/www/html/dom.org/dropplets-blog/dropplets/functions.php on line 110, referer: http://www.dom.org/dropplets-blog/
PHP Notice:  Undefined index: category in /var/www/html/dom.org/dropplets-blog/dropplets/functions.php on line 146, referer: http://www.dom.org/dropplets-blog/
among others and lots of blank screens follow. 
Somebody needs to write a basic manual on what the EXACT post syntax is including the header of the post. Also it would be nice if the software could say "file so and so was not found" or "you messed  up your post so and so".
This is where I gave up since I could not find the information to easily track down the errors. Sorry.

**Comment by markjd84** [comment]
+1 from me... the 'thirty second install' sounds great but in practice there are some unsatisfied dependencies or something. I get the same error messages as above.

I am really keen to find something like this that can help put up a Markdown-authored blog/site with minimal install or maintenance. Have been using WordPress but it's just too sluggish. Another thing I had been wondering about is a simple wrapper for something like [Parsedown](http://parsedown.org/)

Might get a chance to play around and see if I can fix error, as I like the style of posts that Dropplets seems to support
