### ISSUE TITLE
view on mobile devices

### ISSUE THREAD

**Issue by phars** [Circa75/dropplets#379]
Is there a way to disable the switching to mobile view based on the user agent? i'd like to display the articles just as they are displayed "normally" (on a computer screen) - there are no thumbnails on mobile and the \<li\> elements (near the thumbnails) are missing, too.

Any ideas?

**Comment by benlk** [comment]
It's the CSS. It's not based on the useragent - it's based on the width of the mobile browser. If you want, you can go into the template and remove all the `display:none;` rules in the `@media` queries.

**Comment by phars** [comment]
Yep, that's it. Many thanks!
