### ISSUE TITLE
Won't install...

### ISSUE THREAD

**Issue by patmaclondon** [Circa75/dropplets#381]
All is pretty vague about this, the 30 seconds to install is out the window for me, I tried the following : Created a folder called blog, installed Dropplets inside the folder, it comes up with a message saying "It seems that your config folder is not writable, please add the necessary permissions." So it was google to the rescue or so I thought. I read on several pages that it's not the config folder, but there has to be a writable config.php file, great, so I created a new config.php file, now I get a blank index page, with nothing in it. So I decided to install it onto the root of the website, same problem. then I did a chmod of 777 to all files and folders, still same problem. So I decided to SSH into the server and do a UNIX command line install from github... Guess what, still the same blank page, or the password page with that ennoying message about permissions. It's the lack of documentation of this problem that really irritates me, one site even sugested to change apache settings, uhhh no I have multiple websites running. And before you ask, yes PHP is installed, SQL is, en all the rest. Wordpress no problem, joomla no problem, MyBB no problem, THEY HAVE DOCUMENTATION. As it stands I will give this software a big fat 0 out of 10 very dissapointed, if there is someone out there that has a solution, please share.

**Comment by hitecherik** [comment]
I had the same problem and I managed to solve it:

1. `cd` into the parent folder of your Dropplets installation *(so if you unziped the directory into `html/dropplets`, `cd` into the `html` directory)*.
2. Use `chmod` to recursively add write permissions to the other group *(using the same example as above: `sudo chmod -R o+w dropplets`)*
3. Reload the installation page. Dropplets shouldn't output an error now.

Hope this helps.

**Comment by patmaclondon** [comment]
I gave up and moved on... Sometimes just cut your losses, and find another solution The worst thing in my job is finding something and spend hours and hours to install, just to find out it not what you're looking for anyway, and reverse engineering is also a nightmare.
