### ISSUE TITLE
Link back to Dropplets site from GitHub.

### ISSUE THREAD

**Issue by GloverDonovan** [Circa75/dropplets#382]
It would be nice if the GitHub repo had a link back to the Dropplets website. (:

http://dropplets.com/

**Comment by arvislacis** [comment]
@johnroper100 Shouldn't be hard to fix this. In GitHub repo main page click edit and specify http://dropplets.com/ URL in Website field.
![website](https://cloud.githubusercontent.com/assets/626982/15060552/5d0ad458-1334-11e6-9d0e-5f315be613b9.png)

**Comment by johnroper100** [comment]
I'll try, I don' t know if I have the permissions.

**Comment by johnroper100** [comment]
Sorry, but I don't
