### ISSUE TITLE
Missing dropplets.jpg from clean install

### ISSUE THREAD

**Issue by dimo414** [Circa75/dropplets#383]
In a clean install (to a subdirectory, if that's relevant) the images on the homepage are broken.  Copying `http://dropplets.com/demo/cache/dropplets.jpg` to `/path/to/dropplets/cache/` looks like it corrects the issue, but it's an unpleasant way to start.

**Comment by toddbranch** [comment]
:+1: I see this as well - disconcerting for a first-time user.

**Comment by float-mode** [comment]
YEah for some reason clean install brings up broken images in all spots.. confusing at first..

**Comment by mircoboschi** [comment]
I can confirm that images are broken at first install

**Comment by IRDeNial** [comment]
Images are trying to be pulled from here:
http://dropplets.com/profiles/?id=dropplets

They might be relying on the old Twitter API, so it's not pulling it in correctly.

This can be seen here:
https://github.com/Circa75/dropplets/blob/master/dropplets/functions.php#L325

Simple fix is to just grab the user image yourself and save it as "dropplets.jpg".  I might rewrite this function in a few hours and submit a pull request.  Will keep you guys updated.

**Comment by leiza** [comment]
Hello, FYI, just installed dropplets in my web server yesterday and still getting the broken image. Thanks!

**Comment by dimo414** [comment]
This project seems unmaintained (last commit May '14). I decided to use [Hugo](http://gohugo.io/) instead, which has much better support and is being actively developed.

**Comment by IRDeNial** [comment]
@dimo414
I'm working on getting some issues fixed and moving through everything.  Sorry for taking so long.
If you feel that something can be improved, feel free to create a pull request with the desired changes and I can look it over.
