### ISSUE TITLE
404 page does not actually send a 404 response code.

### ISSUE THREAD

**Issue by dimo414** [Circa75/dropplets#384]
Requests that end up loading `404.php` should send a 404 response code.  Presently they return 200.

    $ wget --server-response http://dropplets.com/demo/this-url-does-not-exist -O /dev/null 2>&1 | grep HTTP/
      HTTP/1.1 200 OK

**Comment by bsiege** [comment]
i second that. i have many requests from old blog with outdated URI's. Should definitive give 404

**Comment by bsiege** [comment]
my (ugly) workaround:
prepend 404.php as following

```
<?php
header("HTTP/1.0 404 Not Found");
?>

<article class="single not-found">
    <div class="row">
        <div class="one-quarter meta">
            <div class="thumbnail">
            </div>
        </div>
	<div class="three-quarters post">
	<h1><?php echo($error_title); ?></h1>
            <p><?php echo($error_text); ?></p>

            <ul class="actions">
                <li><a class="button" href="<?php echo($blog_url); ?>">More Articles</a></li>
            </ul>
        </div>
    </div>
</article>
```

**Comment by dimo414** [comment]
Tangential to this issue, but if you have old URLs you should 301 them to their new locations wherever possible, rather than 404ing.
