### ISSUE TITLE
500 - Internal server error after submit password

### ISSUE THREAD

**Issue by matthewcanty** [Circa75/dropplets#386]
I'm hosting this on Fasthosts using their basic hosting package. PHP set to version 5.6.

Here are the steps I am taking. 

1. Upload unzipped Dropplet files to `htdocs`.
2. Navigate to website.
3. Enter password and click submit.
4. 500 - Internal server error.

Password attempts "a", "something-complicated" and a randomly generated complicated string.

Following advice from other issues, I have tried removing the following line from .htaccess.

`Options +FollowSymLinks -MultiViews`

**Comment by ossar** [comment]
Your dropplets directory is writable by Apache  user?
