### ISSUE TITLE
uploaded image not displaying in templates

### ISSUE THREAD

**Issue by brah-dette** [Circa75/dropplets#387]
Hi,

I add dropplets to my webserver, and don't see the icon images. I upload a markdown file post along with an image, the content shows, but still no images. Any thoughts?

Also, I'm getting funny characters on firefox, is this normal?

![screenshot](https://cloud.githubusercontent.com/assets/13284638/8659793/f24e65e2-2961-11e5-9f51-cb8e8d99570d.png)

Thank you.

**Comment by benlk** [comment]
Your image will need to have the same filename as the markdown file, but end in .jpg:

    2015-03-06-post-title.md
    2015-03-06-post-title.jpg

**Comment by brah-dette** [comment]
Hi Ben,

Thanks for the reply. 

Much appreciated,
Amber
