### ISSUE TITLE
error_log generation when no articles

### ISSUE THREAD

**Issue by Cranite** [Circa75/dropplets#388]
When there are no articles (at all, even the welcome one is deleted), an error_log is generated as PHP is attempting to sort an empty array. This is fixed by putting the sort script inside an if statement that returns true when the count() of the array is above zero.

**Comment by Evasitr** [comment]
> if ( count($files) > 0 ) {
>    array_multisort($post_dates, SORT_DESC, $files);
> }

In case anyone was wondering.
