### ISSUE TITLE
Filter category post from index.php?category=some+thing

### ISSUE THREAD

**Issue by texervn** [Circa75/dropplets#390]
Hello,

I am using your great CMS for my blog. Because of some restrictions on using .htaccess, I would like to use direct links for posts and categories. However, when I try this
http://dropplets.com/demo/index.php?category=transportation
It doesn't work.

On the other hand, this link: http://dropplets.com/demo/index.php?filename=the-permanent-way
works perfectly.

Any help, please.

Thanks.

**Comment by taylor-chen** [comment]
Might not be ideal, but you can always do it like this:
http://dropplets.com/demo/index.php?filename=category/transportation
