### ISSUE TITLE
Remove "What's this "in dropplets panel?

### ISSUE THREAD

**Issue by Arshadriyaz** [Circa75/dropplets#391]
How do I remove the "What's this " text along with the dropplet? Chrome's devTools points to index.php in the simple template(Which is currently in use) but when I edit the code in the file, I can't find anything on the dropplets panel. Editing the elements on devTools as HTML was simple but I couldn't find the file to work with in dropplets. I'd really appreciate help on this, since I really like dropplets and want this to work(I've tried loads of other cmss with many of them lacking in some needed place.)

**Comment by Fluxeneine** [comment]
My bad, the code was in tools.php.

**Comment by benlk** [comment]
I'm glad you were able to find it. Mind closing this ticket?
