### ISSUE TITLE
Change dropplets-icon

### ISSUE THREAD

**Issue by Arshadriyaz** [Circa75/dropplets#392]
How can I change the dp-dropplets icon that when clicked opens the tools? Is modifying the dropplets ttf the only way to change this to something else?

**Comment by benlk** [comment]
The icon is set through something in the default dropplets stylesheet, so you could change that rule or override it with your theme's css.

**Comment by IRDeNial** [comment]
You would change it here:
https://github.com/Circa75/dropplets/blob/master/dropplets/style/style.css#L215

This would give you the ability to change how the dropplet icon looks.
You could also set ```font-size: 0;``` and then just insert your own image as a background image.

If you're looking to change the icon itself, you can do one of two things:

1. Change https://github.com/Circa75/dropplets/blob/master/dropplets/style/style.css#L160 and https://github.com/Circa75/dropplets/blob/master/dropplets/style/style.css#L169 as fit.
2. Use your own fonts & icons, which would need modification of the theme files.
