### ISSUE TITLE
Dropplets panel is displayed incorrectly

### ISSUE THREAD

**Issue by AlexL777** [Circa75/dropplets#396]
Hello Developers,

I have just installed dropplets the latest version and the panel in the left corner is displayed incorrectly.

I'll show you here in the screenshot.

Is it a bug?

Thanks in advance.
![dropplets-panel](https://cloud.githubusercontent.com/assets/7885632/12652260/4ab82c98-c5ea-11e5-9bd3-63100d0023c2.jpg)

**Comment by amlette** [comment]
@AlexL777 
Hello,

The file _./cache/dropplets.jpg_ is corrupt in the last version (1.6.2.6).
Find correct image's file here : [dropplets.jpg](http://dropplets.com/demo/cache/dropplets.jpg) and replace it.

Regards.

**Comment by AlexL777** [comment]
Thank you, the problem I have thus achieved and have more questions. I make then even further Issues.
