### ISSUE TITLE
How to Create a Blog Navigation - Dropplets CMS last Version

### ISSUE THREAD

**Issue by AlexL777** [Circa75/dropplets#397]
Hello Developers,

that you have to write the blog posts offline when dropplets CMS, is the first time is not the problem. But how can I create a navigation in frontend.

It should be possible that my readers read your blog post and can go back to the blog Home.

It would also be important in Germany that you include an imprint and privacy in the blog.

How to create static pages with dropplets?

Thanks in advance.

**Comment by AlexL777** [comment]
I think I've found it, as my readers can come back to the blog post index from a blog post out.

There are under each blog post and in the categories of the button "More Articles". If that is seen, it should be enough as navigation. So I could leave it at that.

Maybe you have other info for me. Since I am looking forward :smile:

**Comment by benlk** [comment]
As far as I know, there's no way to create a static page using Dropplets' built-in functionality.

If you want to do it by hand, you could create an HTML page and place it somewhere accessible in your site's filesystem. Your top-level directory might then look like this:

```
.htaccess
cache/
config.php
dropplets/
index.php
jquery-1.10.2.min.js
plugins/
posts/
static/
templates/
imprint.html
```

And then in your theme's template, you would link to `/imprint.html`

If you wanted, you could copy all the template-related parts of Dropplets' `index.php` and use them to build a static-looking page, but which still uses your theme's template files. You would still link to `imprint.php`, but now it would use your theme's files.

**Comment by BullzLabz** [comment]
Hi, how to add a simple page in the active template folder linked like this in the home page `<a href="<?php echo($template_dir_url); ?>about.php">Tuts</a>ˋ and use all php functions (eg. ˋ<?php get header()? > ˋ... etc) without error !
