### ISSUE TITLE
Where do you find dropplets Plugins

### ISSUE THREAD

**Issue by AlexL777** [Circa75/dropplets#398]
Hello Developers,

certainly a simple question for you, but I can not find even the dropplets plugins.

I am thinking of all plugins available for it and to Disqus comments.

Would Disqus when dropplet CMS feasible? It is simply more practical lot, because you can comment on the blog and not on Twitter.

Thanks in advance.

**Comment by AlexL777** [comment]
DISQUS you can integrate well and that goes without plugin. Your created an account on http://disqus.com and remain there Enter the new website dropplets, ie a shortname is you need.

Then you get finally the universal code to include in the file **/templates/simple/post.php**.

There almost below the embed code.

Then you open the selfsame template directory the **index.php** file and inserts under the first body tag this code.

    <script id="dsq-count-scr" src="//droppletsdeblog.disqus.com/count.js" async></script>

Your Shortname will then be accordingly your Shortname.

I would say that I find it cool and light that dropplets CMS can do with it some and you can then embed codes.

Thanks for that

**Comment by benlk** [comment]
As far as I know, there are no publicly-available plugins for Dropplets. Nor are there any plugin repositories.

**Comment by AlexL777** [comment]
Ok, thank you very much for your answer. Then I'll work so.

**Comment by johnroper100** [comment]
There is one known plugin [called Pagelets](https://github.com/adamjacob/Pagelets).
