### ISSUE TITLE
Add new simple about page in folder template!

### ISSUE THREAD

**Issue by BullzLabz** [Circa75/dropplets#401]
Hi everybody, 

I wanted to know how to add a simple about page with all php functions available for index page (so, get_header, get_footer ... etc) without fatal error - "Fatal error: Call to undefined function get_header() in /disk1/web/dropplets/templates/gilson/about.php on line 19"

I tried to add this new page in settings.php, like this = $about_file = $template_dir . 'about.php';

But, problem is the same

**Comment by johnroper100** [comment]
You are going to have to put more of your code here. If you want to add pages, try out this plugin [called Pagelets](https://github.com/adamjacob/Pagelets).

**Comment by BullzLabz** [comment]
Thanks a lot @johnroper100

**Comment by johnroper100** [comment]
No problem!
