### ISSUE TITLE
Why aren't fonts fetched via https?

### ISSUE THREAD

**Issue by Azeirah** [Circa75/dropplets#403]
The fonts in dropplets/templates/index.php fetched from google fonts are fetched via http. Is there a good reason for this, or can I create a pull-request to change it to https?

**Comment by johnroper100** [comment]
Create a pull request!

**Comment by Azeirah** [comment]
Will do

**Comment by Azeirah** [comment]
[pull request](https://github.com/Circa75/dropplets/pull/404)
