### ISSUE TITLE
config.php $blog_url is incorrect for fresh install

### ISSUE THREAD

**Issue by dpower76** [Circa75/dropplets#405]
After doing a fresh install of dropplet, after setting my password and being taken to the main site landing page, all of the styles, etc. were broken - opening up the web debugger console showed me that Dropplet was deriving the path as:
`<myserver>/<path to dropplet>/index.php<name of file that system is looking for>`
instead of:
`<myserver>/<path to dropplet>/<name of file that system is looking for>`

I edited the config.php and changed the `$blog_url` variable to the second path outlined above for things to work correctly. 

But as a new user (luckily PHP savvy) I was about to walk away....

**Comment by dpower76** [comment]
Let me append to this slightly - it seems as if this is necessary to be the former value for processing of blog posts and other pages (although even then it seems 'off'. But I am right with the fact that stylesheets will not load. Therefore In the config.php I did the following:

```
$blog_url = "<base URL of my droplets install>/";
$blog_url_query = $blog_url.'index.php?';
```

Then within the index.php, I adjusted the code within the 'home page' section related to blog post link generation to:

```
            if ($category) {
                $post_link = trim(strtolower($post_category)).'/'.str_replace(FILE_EXT, '', $post['fname']);
            } else {
				$post_link = $blog_url_query.'filename=';
                $post_link = $post_link.str_replace(FILE_EXT, '', $post['fname']);
            }
```

Finally, I took the liberty of changing the image presentation code to:
- fallback to the default image on the site where a post image does not exist AND a twitter image does not exist.

**Comment by johnroper100** [comment]
Did you do this on a release zip or from the latest master commit?

**Comment by johnroper100** [comment]
@dpower76 ?

**Comment by zessx** [comment]
I also noticed a few problems with `$blog_url`, and used the `BASE_URL` constant instead. A whole cleanup would be welcome.
