### ISSUE TITLE
Premium Templates issuing a lot of traffic

### ISSUE THREAD

**Issue by achiminator** [Circa75/dropplets#407]
Hey there,

I really can understand that selling premium templates is a good way to finance this free project, really. I'm thinking this is a great open source project. But I strongly disagree with the lot of traffic this actual set up is generating. Paypal, Gumroad, facebook?!, and a few more I do not know are getting requests while beeing in admin mode. Not only that his slows this beautiful CMS down, it also undermines the pupose for what it was planned: Be able to blog even with a highly unstable connection.

There has to be another way to show these kind of templates without connecting to all these sources. Like showing just the purchasable templates and then, when showing interest, linking to this payment providers etc. At the moment, I just can try to disable this feature, but getting up to date for styles is still interesting.

**Comment by johnroper100** [comment]
Yea, I am working on ways to work with this now. If you have the pages version, you get many themes installed. For now, just go to dropplets/tools.php and delete lines 228 to 277.
