### ISSUE TITLE
Toolbar panel (#dp-dropplet) not working with HTTPS

### ISSUE THREAD

**Issue by jonayls** [Circa75/dropplets#408]
Hello, I have this issue. I installed a dropplet, I chose a password etc etc. But then, when I tried to open the toolbar by clicking the dropplet at the top left corner, it didnt work, the toolbar panel didnt show up.

I realised that my SSL certificate was blocking some HTTP elements so I disabled it and then I was able to open the toolbar panel. 

Any solution for this? I don't want to disable SSL in order to open the panel.

Thanks you in advance!

**Comment by jonayls** [comment]
Hi, I already fixed it. To fix this you have to change the dropplets/functions.php file

From this:
_function get_footer() { ?>
    
    <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>_

To this:
_function get_footer() { ?>
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>_

And now is working properly.

**Comment by johnroper100** [comment]
Thanks for the info!
