### ISSUE TITLE
Dropplet's version number does not change after the update

### ISSUE THREAD

**Issue by AlexL777** [Circa75/dropplets#411]
Hello Developers,

I have today made an update to the latest version. I uploaded the new files to the FTP account and pressed in the backend of Dropplets to "Update". 

Unfortunately it is still the old version 1.6.5. By mail I got but a message that the update has been completed.

Why does not the version number change in the frontend?

Thanks in advance.

**Comment by johnroper100** [comment]
You don't need to upload the files yourself. I just updated the version.
