### ISSUE TITLE
After installation, ':80' gets added to domain name in 'config.php'

### ISSUE THREAD

**Issue by semioticrobotic** [Circa75/dropplets#412]
I'm attempting to use the `$is_home` variable in [my custom template](https://github.com/semioticrobotic/semioticrobotic.net/blob/master/simple/index.php) to display the blog title on the home page (but not on other pages). But that function does not seem to function as I'd expect it to: It does not print the blog title on [the blog home page](http://semioticrobotic.net/dropplets/).

**Comment by semioticrobotic** [comment]
I was able to address this issue by manually editing ``config.php`` and removing ``:80`` from the URL logged in ``blog_url``. I'm not sure how or why this gets added, but that seems like a good place to begin addressing this bug.

**Comment by benlk** [comment]
Suggested title change: "After installing, `:80` is added to domain name in `config.php`"

This is a known bug, but it doesn't have an actual ticket describing it as such.

Tickets that have mentioned `:80` in the past: #18, #234, #243, #272, #278, #354, #409

Most of those tickets were marked by @Circa75 as "Duplicate" without linking to the ticket they duplicate; there is no ticket that documents this problem or a solution.

PR #283 was a partial fix for it, but apparently doesn't hit everywhere.

**Comment by semioticrobotic** [comment]
This is helpful background, @benlk. I will get reading!

**Comment by IDDemon** [comment]
Change line **443** in **index.php** from

```php
$port = $_SERVER["SERVER_PORT"];
```

to

```php
$port = intval($_SERVER["SERVER_PORT"]);
```

and problem solved. 

A much better solution is to change the line to the following code:
```php
// Check if the port number is set. According to php's documentation,
// in some cases Apache 2 may not return the port.
if (isset($_SERVER["SERVER_PORT"])) {
	if (is_string($_SERVER["SERVER_PORT"])) {
		// If it's a string, we should convert it to number
		$port = intval($_SERVER["SERVER_PORT"]);
	} elseif (is_integer($_SERVER["SERVER_PORT"])) {
		// If it's integer, we use it
		$port = $_SERVER["SERVER_PORT"];
	} else {
		// If nothing above, we should go with default port number
		$port = 80;
	}
} else {
	// If not set, we should go with default port number
	$port = 80;
}
// If port is string and not numeric, it will return 0
// Additionaly port number has a range limit
if ($port < 1 || $port > 65535) {
	$port = 80;
}
```

**Comment by johnroper100** [comment]
updated and fixed!
