### ISSUE TITLE
Path mixup...

### ISSUE THREAD

**Issue by tilllt** [Circa75/dropplets#414]
I installed Dropplets in a subdir, working _almost_ fine on my nginx webserver, using this location block:

location /blog/ {
		alias /usr/share/nginx/www/blog/;
		try_files $uri $uri/ $uri/index.php /blog/index.php?filename=$uri;
	}

The problem is that dropplets is confused about the directories it needs. it tries to find the "cache" directory in "/usr/share/nginx/www/cache" instead of "/usr/share/nginx/www/blog/cache" since the templates html references the cache dir like this "../cache/" - also downloading the starter post fails. it loads css and js scripts fine though, so it seems there referencing of the root dir / relative dirs is not coherent. Or (very probable) a nginx configuration error on my side?

**Comment by johnroper100** [comment]
I believe this is fixed
