### ISSUE TITLE
Drafts appear in Feed

### ISSUE THREAD

**Issue by tywunon** [Circa75/dropplets#415]
every file in posts/ appearing in the RSS feed! even if they are marked as draft. is this on purpose?

**Comment by IDDemon** [comment]
Edit **index.php** file and find the line 236 which contains a foreach:

```php
foreach($posts as $post) {
```

and after that line add the following:

```php
if ($post['post_status'] == 'draft') continue;
```

**Comment by johnroper100** [comment]
Fixed!
