### ISSUE TITLE
Dropplets still pinging Gumroad and PayPal

### ISSUE THREAD

**Issue by semioticrobotic** [Circa75/dropplets#416]
As the title says. This happens on home page loads and reloads, and I suspect it's related to a bygone era in which users could purchase @Circa75 templates directly through the sidebar. Can we remove this now to streamline the platform?

**Comment by benlk** [comment]
gumroad: https://github.com/Circa75/dropplets/blob/ab945cdb3411362dc9ed117c2fbc8ea8e9278c45/dropplets/tools.php#L303

I can't find PayPal in the repo; I suspect that's because GumRoad loads PayPal.

**Comment by johnroper100** [comment]
I'll take a look at fixing it

**Comment by johnroper100** [comment]
Fixed!
