### ISSUE TITLE
Restrictive File Permissions Prevent Installation 

### ISSUE THREAD

**Issue by pippinsplugins** [Circa75/dropplets#67]
While doing my first test, I noticed that having restrictive file permissions prevents the installation from working, which is expected, but instead of showing an error of some kind, it just reloads the setup screen with no indication of what the problem was.

**Comment by patmaclondon** [comment]
All is pretty vague about this, the 30 seconds to install is out the window for me, I tried the following : Created a folder called blog, installed Dropplets inside the folder, it comes up with a message saying "It seems that your config folder is not writable, please add the necessary permissions." So it was google to the rescue or so I thought. I read on several pages that it's not the config folder, but there has to be a writable config.php file, great, so I created a new config.php file, now I get a blank index page, with nothing in it. So I decided to install it onto the root of the website, same problem. then I a chmod of 777 to all files and folders, still same problem. So I decided to SSH into the server and do a UNIX command line install from github... Guess what, still the same blank page, or the password page with that ennoying message about permissions. It's the lack of documentation of this problem that really irritates me, one site even sugested to change apache settings, uhhh no I have multiple websites running. And before you ask, yes PHP is installed, SQL is, en all the rest. Wordpress no problem, joomla no problem, MyBB no problem, THEY HAVE DOCUMENTATION. As it stands I will give this software a big fat 0 out of 10, and I will try some other package.
