### ISSUE TITLE
Markdown Extra as default

### ISSUE THREAD

**Issue by kaijen** [Circa75/dropplets#87]
Hello, 

as much as I hate to see the [diverging development](http://www.leancrew.com/all-this/2010/10/thoughts-on-markdown/) of Markdown syntax, I personally regard the original [Markdown Syntax](http://daringfireball.net/projects/markdown/syntax) as too limited.

I'd love to see [PHP Markdown Extra](http://michelf.ca/projects/php-markdown/extra/) as the default plugin with Dropplets as a replacement for the default version. I implemented this in my (test) blog and it did not seem to break anything but provide the extra features on request.

Any chance, you'll change that?

Best Regards, .kai

**Comment by johnroper100** [comment]
This is a pull request now.
